local serialize = {}
local save_tampered = false
local saves_locked = false
local current_slot = nil   -- which save slot the game is playing in; every save is mirrored into it
local current_prefix = ""

-- keyed hash secret: this is deterrence, not security, since the game ships its own source
local SIGNING_SECRET = "v0yage-0f-the-b34ten-0nes"

-- the weak checksum older saves were signed with; only used to recognise them and re-sign them
local function legacy_save_hash(str)
    local hash = 5381
    for i = 1, #str do
        hash = (hash * 33 + str:byte(i)) % 4294967296
    end
    return string.format("%08x", hash)
end

local function to_hex(raw)
    return (raw:gsub(".", function(c)
        return string.format("%02x", c:byte())
    end))
end

local function save_hash(str)
    return to_hex(love.data.hash("sha256", SIGNING_SECRET .. "|save|" .. str .. "|" .. SIGNING_SECRET:reverse()))
end

-- A save is only tampered with if it carries a signature that does not match it. A file with no signature at
-- all was simply added (a dropped-in save, a playtest save), so it is trusted and gets signed on load.
local function signature_matches(content, signature)
    if not signature then
        return true
    end
    signature = signature:gsub("%s+$", "")
    return signature == save_hash(content) or signature == legacy_save_hash(content)
end

-- the signature file that goes with a data file: save.lua -> save.sig
local function sig_path_for(lua_path)
    return (lua_path:gsub("%.lua$", ".sig"))
end

--[[
  From github.com
  Lua Table Serializer/Deserializer

  This script provides two functions:
  1. `serialize(data)`: Converts a Lua table (containing numbers, booleans, strings,
     and nested tables of these types) into a Lua source code string.
  2. `deserialize(str)`: Converts a Lua source code string (generated by `serialize`)
     back into a Lua table.

  Limitations:
  - Does NOT handle functions, userdata, threads, or metatables. These will be
    represented as `nil` or cause an error if not explicitly handled.
  - Does NOT handle circular table references (tables that refer back to themselves
    or their parent tables). This will cause an infinite loop. For complex
    serialization, consider dedicated libraries like 'Ser' or 'bitser'.
  - Deserialization uses `load()`, which executes the string as Lua code. Be cautious
    when deserializing data from untrusted sources, as it could pose a security risk.
]]

--- serializes a lua table into a lua source code string.
-- @param data table the table to serialize.
-- @param indent_level number (optional) the current indentation level for pretty printing.
-- @return string the lua source code string representation of the table.
local function do_serialize(data, indent_level)
    indent_level = indent_level or 0
    local indent_str = string.rep("  ", indent_level)
    local s = ""

    if type(data) == "table" then
        s = s .. "{\n"
        local first_element = true
        for k, v in pairs(data) do
            if not first_element then
                s = s .. ",\n"
            end
            first_element = false

            s = s .. indent_str .. "  " -- indent for key-value pair

            -- serialize key
            if type(k) == "string" then
                s = s .. string.format("[%q]", k) -- use %q for string keys to handle special chars
            elseif type(k) == "number" then
                s = s .. "[" .. tostring(k) .. "]"
            else
                -- for unsupported key types, you might want to error or skip
                error("Unsupported key type for serialization: " .. type(k))
            end

            s = s .. " = "

            -- serialize value recursively
            if type(v) == "table" then
                s = s .. do_serialize(v, indent_level + 1)
            elseif type(v) == "string" then
                s = s .. string.format("%q", v) -- use %q for string values
            elseif type(v) == "number" then
                s = s .. tostring(v)
            elseif type(v) == "boolean" then
                s = s .. tostring(v)
            elseif type(v) == "nil" then
                s = s .. "nil" -- explicitly write nil for clarity, though often omitted
            else
                -- handle unsupported value types (e.g., functions, userdata)
                -- for this basic serializer, we'll represent them as nil and print a warning.
                s = s .. "nil -- [warning: unserializable type '" .. type(v) .. "' replaced with nil]"
            end
        end
        s = s .. "\n" .. indent_str .. "}"
    elseif type(data) == "string" then
        s = string.format("%q", data)
    elseif type(data) == "number" then
        s = tostring(data)
    elseif type(data) == "boolean" then
        s = tostring(data)
    elseif type(data) == "nil" then
        s = "nil"
    else
        -- for top-level unsupported types
        s = "nil -- [warning: unserializable type '" .. type(data) .. "' replaced with nil]"
    end

    return s
end

--- deserializes a lua source code string back into a lua table.
-- @param str string the lua source code string to deserialize.
-- @return table|nil the deserialized table, or nil if an error occurred.
-- @return string|nil an error message if deserialization failed.
local function do_deserialize(str)
    -- wrap the string in `return (...)` to ensure it's treated as an expression
    -- and returns a value, rather than just executing statements.
    local source = "return " .. str
    local chunk, err

    if loadstring then
        -- Lua 5.1 / LuaJIT path.
        chunk, err = loadstring(source)
        if chunk and setfenv then
            setfenv(chunk, {}) -- the file may only describe data; an edited save must not be able to run code
        end
    else
        -- Lua 5.2+ path.
        local ok, result = pcall(load, source, "=save", "t", {})
        if ok and type(result) == "function" then
            chunk = result
        else
            -- Fallback for environments where load expects a reader function.
            local first = true
            chunk, err = load(function()
                if first then
                    first = false
                    return source
                end
                return nil
            end)
        end
    end
    if not chunk then
        return nil, "Syntax error in serialized data: " .. err
    end

    local success, result = pcall(chunk)
    if success then
        return result
    else
        return nil, "Runtime error during deserialization: " .. result
    end
end

function serialize.save_data(data)
    if saves_locked then
        return
    end
    local serialized = do_serialize(data)
    love.filesystem.write("save.lua", serialized)
    love.filesystem.write("save.sig", save_hash(serialized))
    if current_slot then
        local slot_path = current_prefix .. current_slot .. ".lua"
        love.filesystem.write(slot_path, serialized)
        love.filesystem.write(sig_path_for(slot_path), save_hash(serialized))
    end
    print("saved")
end

-- the slot the game saves into from now on (save.lua stays the active copy that the game loads)
function serialize.set_save_slot(slot, prefix)
    current_slot = slot
    current_prefix = prefix or ""
end

function serialize.load_data(options)
    options = options or {}
    local allow_tampered = options.allow_tampered == true
    if not love.filesystem.getInfo("save.lua") then
        save_tampered = false
        return nil
    end
    local content = love.filesystem.read("save.lua")
    if content then
        local expected_sig = love.filesystem.read("save.sig")
        save_tampered = not signature_matches(content, expected_sig)
        if not save_tampered and (not expected_sig or expected_sig:gsub("%s+$", "") ~= save_hash(content)) then
            love.filesystem.write("save.sig", save_hash(content)) -- unsigned or signed the old way: sign it now
        end

        if save_tampered and not allow_tampered then
            return nil
        end
        return do_deserialize(content)
    end
    save_tampered = false
    return nil
end

-- while locked, save_data is a no-op so nothing can rewrite a wiped save
function serialize.set_locked(locked)
    saves_locked = locked == true
end

-- deletes the save, including the slot it is mirrored into (or the slot would hand the run straight back)
function serialize.wipe_save()
    love.filesystem.remove("save.lua")
    love.filesystem.remove("save.sig")
    if current_slot then
        serialize.delete_slot(current_slot, current_prefix)
    end
    save_tampered = false
end

local function slot_path(slot, prefix)
    return (prefix or "") .. tostring(slot) .. ".lua"
end

function serialize.save_manually(data, slot, prefix)
    local path = slot_path(slot, prefix)
    local data_str = do_serialize(data)
    love.filesystem.write(path, data_str)
    love.filesystem.write(sig_path_for(path), save_hash(data_str))
end

-- returns the slot's data, and whether its signature was wrong (nil when the slot is empty)
function serialize.load_manually(slot, prefix)
    local path = slot_path(slot, prefix)
    local data_str = love.filesystem.read(path)
    if not data_str then
        return nil
    end

    local sig_file = sig_path_for(path)
    local current_sig = love.filesystem.read(sig_file)
    local tampered = not signature_matches(data_str, current_sig)
    if not tampered and (not current_sig or current_sig:gsub("%s+$", "") ~= save_hash(data_str)) then
        love.filesystem.write(sig_file, save_hash(data_str)) -- a slot dropped in by hand: sign it
    end
    return do_deserialize(data_str), tampered
end

-- removes a slot's file and its signature; true if the slot is gone
function serialize.delete_slot(slot, prefix)
    local path = slot_path(slot, prefix)
    love.filesystem.remove(sig_path_for(path))
    return love.filesystem.remove(path)
end

-- Persistent state: a plain table that outlives saves. The menu loads it once and keeps it to itself:
--   local persistent = serialize.load_persistent(defaults)
--   persistent.times_beaten = persistent.times_beaten + 1
--   serialize.save_persistent(persistent)
-- Wiping or resetting a save never touches it. It lives in persistent.lua next to a keyed signature
-- (persistent.sig); if the file is edited, it resets to the defaults.
local PERSISTENT_PATH = "persistent.lua"
local PERSISTENT_SIG_PATH = "persistent.sig"
local PERSISTENT_SECRET = SIGNING_SECRET

local function persistent_signature(content)
    return to_hex(love.data.hash("sha256", PERSISTENT_SECRET .. "|" .. content .. "|" .. PERSISTENT_SECRET:reverse()))
end

local function is_storable(value)
    local kind = type(value)
    if kind == "table" then
        for k, v in pairs(value) do
            if (type(k) ~= "string" and type(k) ~= "number") or not is_storable(v) then
                return false
            end
        end
        return true
    end
    return kind == "number" or kind == "string" or kind == "boolean"
end

-- does persistent.lua on disk match its signature? a missing file counts as fine (nothing to tamper with)
local function persistent_file_is_intact()
    if not love.filesystem.getInfo(PERSISTENT_PATH) then
        return true
    end
    local content = love.filesystem.read(PERSISTENT_PATH)
    local signature = love.filesystem.read(PERSISTENT_SIG_PATH)
    return content ~= nil and signature == persistent_signature(content)
end

local function write_persistent(store)
    local content = do_serialize(store)
    love.filesystem.write(PERSISTENT_PATH, content)
    love.filesystem.write(PERSISTENT_SIG_PATH, persistent_signature(content))
end

local function read_persistent()
    if not love.filesystem.getInfo(PERSISTENT_PATH) then
        return {}
    end
    if persistent_file_is_intact() then
        local store = do_deserialize(love.filesystem.read(PERSISTENT_PATH))
        if type(store) == "table" then
            return store
        end
    end
    print("persistent state was tampered with - resetting it")
    write_persistent({})
    return {}
end

-- copies any key `store` is missing from `defaults`, so adding a variable to the defaults file is all it takes
local function fill_defaults(store, defaults)
    for key, default in pairs(defaults) do
        if store[key] == nil then
            if type(default) == "table" then
                store[key] = {}
                fill_defaults(store[key], default)
            else
                store[key] = default
            end
        elseif type(default) == "table" and type(store[key]) == "table" then
            fill_defaults(store[key], default)
        end
    end
    return store
end

function serialize.load_persistent(defaults)
    return fill_defaults(read_persistent(), defaults or {})
end

function serialize.save_persistent(store)
    assert(type(store) == "table" and is_storable(store),
        "persistent state must hold numbers, strings, booleans and tables of those")

    if not persistent_file_is_intact() then
        -- the file was edited while the game ran: empty the table in place and start over from empty
        print("persistent state was tampered with - resetting it")
        for key in pairs(store) do
            store[key] = nil
        end
    end
    write_persistent(store)
end

function serialize.was_tampered()
    return save_tampered
end

return serialize
